title: PEEYUSHSRJ
email: peeyushsrj@gmail.com
description: Problems and their solutions
url: "https://peeyushsrj.github.io"
twitter: peeyu5h

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
