title: PYU.SH
email: peeyushsrj@gmail.com
description: Problems and their solutions
url: "htts://pyu.sh"
twitter: peeyu5h
disqus: peeyushsrj
github: peeyushsrj

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
