title: Peeyu.sh
email: peeyushsrj@gmail.com
description: Problems and their solutions
url: "https://pyu.sh"
twitter: peeyu5h
disqus: peeyushsrj
disqusShortname: peeyushsrj
github: peeyushsrj
baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
